novip: §6Buy VIP now and get the ability to change gamemode and fly!
vip: §4Usage: /vip gmc|gms|fly
gmc: Gamemode changed to §bCreative
gms: Gamemode changed to §aSurvival
flyon: You can fly now!
flyoff: You landed!
noperm: §4You don't have the permission to use this command!
already_in_gamemode: §4You are already in this gamemode!
